name: Deploy Calculator App

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t calculator-app .

      - name: Run Docker container
        run: docker run -d -p 80:80 --name calculator-app calculator-app

      - name: Upload Docker image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker tag calculator-app ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
